# nginx/nginx.conf

user  nginx;
worker_processes  auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 80;

        location / {
            # Serve static files
            root /usr/share/nginx/html;
            index index.html;

            # Enable CORS
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
            add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization' always;

            # Handle OPTIONS requests
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Max-Age' 3600;
                add_header 'Content-Length' 0;
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                return 204;
            }
        }

        # Serve data
        location /data/ {
            alias /data/;
            autoindex on;          # optional: enables directory listing
            add_header 'Access-Control-Allow-Origin' '*';  # enable CORS
        }

        # Reverse proxies

        location /pycsw/ {
            proxy_pass http://pycsw:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            add_header 'Access-Control-Allow-Origin' '*' always;
        }

        location /titiler/ {
            # rewrite ^/titiler(.*)$ $1 break;
            proxy_pass http://titiler:8000/;
            proxy_set_header Host $host;
            proxy_set_header Referer $http_referer;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            add_header 'Access-Control-Allow-Origin' '*' always;
        }

        location /browser/ {
            proxy_pass http://stac-browser:8080/browser/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            add_header 'Access-Control-Allow-Origin' '*' always;
        }

        # Nginx metrics endpoint for Prometheus
        location /nginx_status {
            stub_status;
            allow all;
        }
    }
}
